import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Plus_Jakarta_Sans} from "next/font/google"

import {cn} from '@/lib/util'

const fontSans = Plus_Jakarta_Sans({
  subsets:["latin"],
  variable: "--font-sans",
  weight: ['200','300','400','500','600','700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn('min-h-screen bg-dark-300 font-sanse antialised', fontSans.variable)}
      >
        {children}
      </body>
    </html>
  );
}
